### ISSUE TITLE
Use some system for letters (names of types values etc.) in the spec

### ISSUE THREAD

**Issue by rpominov** [rpominov/static-land#9]
Currently it's a bit of a mess, and we need to invent some sort of naming system...

**Comment by Shard** [comment]
After going over all the laws, some ideas I have:

- Reserve `a,b,c,d,e` for primitive instances and plain objects only.
- `f,g,h,i` and beyond can then be for functions as variables.
- Until `x,y,z`. use these for inline (arrow) functions only.
- Keep capitals restricted to the Algebraic Types being referenced and use the first letter from each type
- If there is a conflict because of referenced types, use a second lowercase letter:

```
T // Traversable
Fu // Functor
Fo // Foldable
```
